### ISSUE TITLE
Unable to de-activate apple pay method

### ISSUE THREAD

**Issue by ankahla** [BitBagCommerce/SyliusMolliePlugin#111]
Thanks for this awsome plugin, I am searching a way to disable apple pay button but I didn't find any thing in admin page / payment methods.
![image](https://user-images.githubusercontent.com/4787799/113043646-0386f000-919d-11eb-908a-0d396cc78fd9.png)

Also I tried this sql but it is not disabling the apple pay button
`UPDATE bitbag_mollie_configuration SET apple_pay_direct = 0 WHERE apple_pay_direct = 1;`

Also I am getting this error in chrome desktop on all pages
![image](https://user-images.githubusercontent.com/4787799/113044019-80b26500-919d-11eb-99ea-2bcc8a5bdb3a.png)

Is there a proper way to disable apple pay button ?

**Comment by daniel8702** [comment]
Hi @ankahla thanks for Your message.
On the SyliusMolliePlugun version 3.3.7, You can disable/enabled ApplePayDirect Button.
 https://github.com/BitBagCommerce/SyliusMolliePlugin/releases/tag/v3.3.7

![image](https://user-images.githubusercontent.com/6348491/113134218-d714b780-9220-11eb-95cf-9b0090cdb1d0.png)

The error is because you do not use a device compatible with Apple and Safari. 
But we will check it :).

**Comment by AmandaMollie** [comment]
@ankahla - Amanda from Mollie here! I'm trying to understand your use case a bit better. How did the Apple Pay direct button get enabled initially if you don't have this method active via Mollie?
